Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define "jenkins-master" do |master|
    master.vm.box = "ubuntu/jammy64"
    master.vm.network "private_network", ip: "192.168.56.10"

    master.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end

    master.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install fontconfig openjdk-21-jre docker.io wget

      systemctl enable docker
      systemctl start docker

      sudo wget -O /etc/apt/keyrings/jenkins-keyring.asc \
      https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
      echo "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc]" \
      https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
      /etc/apt/sources.list.d/jenkins.list > /dev/null
      sudo apt update
      sudo apt install jenkins

      systemctl enable jenkins
      systemctl start jenkins
    SHELL
  end


  config.vm.define "jenkins-worker" do |worker|
    worker.vm.box = "ubuntu/jammy64"
    worker.vm.network "private_network", ip: "192.168.56.11"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 3
    end

    worker.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y openjdk-17-jdk docker.io

      systemctl enable docker
      systemctl start docker
    SHELL
  end

end