Vagrant.configure("2") do |config|

  DB_USER = ENV['DB_USER'] || "petclinic"
  DB_PASS = ENV['DB_PASS'] || "petclinicpass"
  DB_NAME = ENV['DB_NAME'] || "petclinic"

  config.vm.box = "ubuntu/jammy64"

  config.vm.define "DB_VM" do |db|
    db.vm.hostname = "dbvm"
    db.vm.network "private_network", ip: "192.168.56.10"

    db.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    db.vm.provision "shell",
      path: "scripts/db_provision.sh",
      env: {
        "DB_USER" => DB_USER,
        "DB_PASS" => DB_PASS,
        "DB_NAME" => DB_NAME
      }
  end

  config.vm.define "APP_VM" do |app|
    app.vm.hostname = "appvm"
    app.vm.network "private_network", ip: "192.168.56.11"

    app.vm.network "forwarded_port", guest: 8080, host: 8080

    app.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end


    app.vm.provision "shell",
      path: "scripts/app_provision.sh",
      env: {
        "DB_HOST" => "192.168.56.10",
        "DB_PORT" => "3306",
        "DB_USER" => DB_USER,
        "DB_PASS" => DB_PASS,
        "DB_NAME" => DB_NAME
      }
  end

end
